### ISSUE TITLE
How to emulate keypress?

### ISSUE THREAD

**Issue by zhum** [kui/ruinput#1]
Hello! I need to emulate keyboard (and later - mouse). uinuput is the best way to do this, as I see in other projects. I want to use ruinput gem, but cannot figure out how to send virtulal keypress... Can you drop just few lines for illustrate this?

Thank you!

**Comment by zhum** [comment]
Anyone??

**Comment by kui** [comment]
!
Hi, @zhum. Sorry for the delay.

umm...
Can you execute scripts in `sample` directory?

**Comment by zhum** [comment]
Of course, I did :) But I cannot find list of constatnts for all keys. E.g. I need to press Shift+Tab, or Left_arrow, or Ctrl+Enter... I think I need to use approach from input_j sample, but I cannot understand what must replace 'KEY_J' constant.

Also I wonder if I can emulate mouse events? If yes, how to do this (I think mouse moves are different from input_j example).

**Comment by kui** [comment]
> I cannot find list of constatnts for all keys.

`KEY_J` or other constants is defined by [revdev.c](/kui/revdev/blob/master/ext/revdev/revdev.c) in [revdev](/kui/revdev) package.

[revdev.c](/kui/revdev/blob/master/ext/revdev/revdev.c) import constants, such as `KEY_*`, `BTN_*`, etc, from `/usr/src/linux-headers-xxxxx/include/linux/input.h`, so you can found these difinition of constants in `input.h`.

---

> I wonder if I can emulate mouse events?

Actually, I did not try emulate mouse events. I think:
- mouse buttoms: `BTN_LEFT`, `BTN_RIGHT` and `BTN_MIDDLE`
- mouse move: `ABS_X`, `ABS_Y`, `REL_X` and `REL_Y`
- mouse wheel: `ABS_WHEEL` and `REL_WHEEL`

These constants be also defined [revdev.c](/kui/revdev/blob/master/ext/revdev/revdev.c) (originally `input.h`).

**Comment by kui** [comment]
And [the sample scripts in revdev](/kui/revdev/tree/master/sample) will be of some help (In particular `key_dump`)

`key_dump` dump your device event. So the dump of your mouse events will help you also.
